table China_Cars_Exp_Flat
	lineageTag: 28f83abe-3609-4a9d-82de-c4df2b285f48

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 43d32334-bcc1-41e4-ae08-887293082e36
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: bfced3b4-c222-4ca7-ab20-feda20294009
		summarizeBy: none
		sourceColumn: Reporter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Flow
		dataType: string
		lineageTag: 25cd4d36-155a-4361-8adc-10a307916ddb
		summarizeBy: none
		sourceColumn: Flow

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Partner Code'
		dataType: int64
		formatString: 0
		lineageTag: 5b573396-7b68-4c9e-a2d9-e990eff95d81
		summarizeBy: none
		sourceColumn: Partner Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Partner ISO'
		dataType: string
		lineageTag: d3ae15cf-3196-4a34-9964-e7762c9c34bb
		summarizeBy: none
		sourceColumn: Partner ISO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Partner
		dataType: string
		lineageTag: 9e177998-818d-4c40-960c-1e5bebfe7a28
		summarizeBy: none
		sourceColumn: Partner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Vehicle Category'
		dataType: string
		lineageTag: 1b6116a2-8458-4ca9-bca8-02b88241a9cf
		summarizeBy: none
		sourceColumn: Vehicle Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sub Category'
		dataType: string
		lineageTag: 69d03363-b89d-46cf-bdbd-df0cdf0360c3
		summarizeBy: none
		sourceColumn: Sub Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'HS Code'
		dataType: string
		lineageTag: e7ac37fa-0d0e-449d-b52f-2cafb14c5b9f
		summarizeBy: none
		sourceColumn: HS Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'HS Description'
		dataType: string
		lineageTag: 5e930447-1b5e-42ff-88e0-229e331d1c84
		summarizeBy: none
		sourceColumn: HS Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'HS Classification'
		dataType: string
		lineageTag: 899ca7a4-d92d-459d-af89-1e75e0b21732
		summarizeBy: none
		sourceColumn: HS Classification

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Trade Value USD'
		dataType: double
		lineageTag: 6bdb0956-1d4c-408d-8092-5c15d573f247
		summarizeBy: sum
		sourceColumn: Trade Value USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FOB Value USD'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3366cced-0291-490f-b654-99bc74242ede
		summarizeBy: sum
		sourceColumn: FOB Value USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'CIF Value USD'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a9e42989-4733-4599-b6e2-49de990acc01
		summarizeBy: sum
		sourceColumn: CIF Value USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Quantity
		dataType: double
		lineageTag: 128c2dbf-e89c-4262-a613-a544a10c4710
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quantity Unit'
		dataType: string
		lineageTag: 044176e7-c3c5-4ea0-a875-51a06dc148b1
		summarizeBy: none
		sourceColumn: Quantity Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Net Weight KG'
		dataType: double
		lineageTag: eccff23a-8621-48f7-9e56-3f6cb8ad4d02
		summarizeBy: sum
		sourceColumn: Net Weight KG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price USD'
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5b926a4b-1db7-4699-a76a-1f1a77e20d20
		summarizeBy: sum
		sourceColumn: Unit Price USD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Value USD per KG'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 66815245-03bd-4049-b565-250bad7a5070
		summarizeBy: sum
		sourceColumn: Value USD per KG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition China_Cars_Exp_Flat = m
		mode: import
		source = ```
				let
				    // ============================================================
				    // UN COMTRADE - CHINA PASSENGER CAR EXPORTS BY MOTOR TYPE
				    // ============================================================
				
				    ApiKey = "5101f112cd1a43ba97fd22d4409d20a5",
				
				    // 1. YEARS
				    StartYear = 2022,
				    CurrentYear = Date.Year(DateTime.LocalNow()),
				    Years = {StartYear..CurrentYear},
				    Periods = Text.Combine(List.Transform(Years, each Text.From(_)), ","),
				
				    // 2. QUERY PARAMETERS
				    ReporterCode = "156",
				    FlowCode = "X",
				    
				    // Explicit 6-digit codes for all 8703 motor types
				    CarHS6Digit = "870310,870321,870322,870323,870324,870331,870332,870333,870340,870350,870360,870370,870380,870390",
				
				    // 3. API REQUEST
				    ApiUrl = "https://comtradeapi.un.org/data/v1/get/C/A/HS",
				    
				    Source = Json.Document(
				        Web.Contents(
				            ApiUrl,
				            [
				                Query = [
				                    cmdCode = CarHS6Digit,
				                    period = Periods,
				                    reporterCode = ReporterCode,
				                    flowCode = FlowCode,
				                    partner2Code = "0",
				                    motCode = "0",
				                    customsCode = "C00",
				                    maxRecords = "100000",
				                    includeDesc = "true"
				                ],
				                Headers = [
				                    #"Ocp-Apim-Subscription-Key" = ApiKey,
				                    Accept = "application/json"
				                ],
				                Timeout = #duration(0, 0, 5, 0)
				            ]
				        )
				    ),
				
				    // 4. EXTRACT DATA ARRAY
				    Data = if Record.HasFields(Source, "data") then Source[data] else {},
				    RawTable = if List.Count(Data) > 0 then Table.FromRecords(Data) else #table({}, {}),
				
				    // 5. EXPAND COLUMNS
				    ExpandedTable = Table.SelectColumns(
				        RawTable,
				        {
				            "refYear", "reporterCode", "reporterISO", "reporterDesc",
				            "flowCode", "flowDesc", "partnerCode", "partnerISO", "partnerDesc",
				            "cmdCode", "cmdDesc", "classificationCode", "qtyUnitCode",
				            "qtyUnitAbbr", "qty", "netWgt", "fobvalue", "cifvalue", "primaryValue"
				        },
				        MissingField.UseNull
				    ),
				
				    // 6. RENAME COLUMNS
				    RenamedColumns = Table.RenameColumns(
				        ExpandedTable,
				        {
				            {"refYear", "Year"},
				            {"reporterCode", "Reporter Code"},
				            {"reporterISO", "Reporter ISO"},
				            {"reporterDesc", "Reporter"},
				            {"flowCode", "Flow Code"},
				            {"flowDesc", "Flow"},
				            {"partnerCode", "Partner Code"},
				            {"partnerISO", "Partner ISO"},
				            {"partnerDesc", "Partner"},
				            {"cmdCode", "HS Code"},
				            {"cmdDesc", "HS Description"},
				            {"classificationCode", "HS Classification"},
				            {"qtyUnitCode", "Quantity Unit Code"},
				            {"qtyUnitAbbr", "Quantity Unit"},
				            {"qty", "Quantity"},
				            {"netWgt", "Net Weight KG"},
				            {"fobvalue", "FOB Value USD"},
				            {"cifvalue", "CIF Value USD"},
				            {"primaryValue", "Trade Value USD"}
				        },
				        MissingField.Ignore
				    ),
				
				    // 7. FILTER EXPORTS & EXCLUDE CHINA DOMESTIC
				    ExportsOnly = Table.SelectRows(RenamedColumns, each ([Flow Code] = "X")),
				    ExcludeChina = Table.SelectRows(ExportsOnly, each ([Partner Code] <> 156 and [Partner ISO] <> "CHN")),
				
				    // 8. ADD VEHICLE CATEGORY
				    AddVehicleCategory = Table.AddColumn(
				        ExcludeChina,
				        "Vehicle Category",
				        each "Passenger Cars",
				        type text
				    ),
				
				    // 9. ADD MOTOR SUB-CATEGORY
				    AddSubCategory = Table.AddColumn(
				        AddVehicleCategory,
				        "Sub Category",
				        each
				            let hs = Text.From([HS Code]) in
				            
				            if Text.StartsWith(hs, "870380") then "Battery Electric Vehicle (BEV)"
				            else if Text.StartsWith(hs, "870360") then "Gasoline Plug-In Hybrid (PHEV)"
				            else if Text.StartsWith(hs, "870370") then "Diesel Plug-In Hybrid (PHEV)"
				            else if Text.StartsWith(hs, "870340") then "Gasoline Hybrid (HEV)"
				            else if Text.StartsWith(hs, "870350") then "Diesel Hybrid (HEV)"
				            else if Text.StartsWith(hs, "870321") then "Gasoline ICE (<= 1000 cc)"
				            else if Text.StartsWith(hs, "870322") then "Gasoline ICE (1000-1500 cc)"
				            else if Text.StartsWith(hs, "870323") then "Gasoline ICE (1500-3000 cc)"
				            else if Text.StartsWith(hs, "870324") then "Gasoline ICE (> 3000 cc)"
				            else if Text.StartsWith(hs, "870331") then "Diesel ICE (<= 1500 cc)"
				            else if Text.StartsWith(hs, "870332") then "Diesel ICE (1500-2500 cc)"
				            else if Text.StartsWith(hs, "870333") then "Diesel ICE (> 2500 cc)"
				            else if Text.StartsWith(hs, "870390") then "Fuel Cell / Hydrogen / Other"
				            else if Text.StartsWith(hs, "870310") then "Golf Carts & Snow Vehicles"
				            else "Unmapped Passenger Car",
				        type text
				    ),
				
				    // 10. CALCULATE METRICS
				    AddUnitPrice = Table.AddColumn(
				        AddSubCategory,
				        "Unit Price USD",
				        each if [Quantity] <> null and [Quantity] > 0 and [Trade Value USD] <> null 
				             then [Trade Value USD] / [Quantity] 
				             else null,
				        type number
				    ),
				
				    AddValuePerKg = Table.AddColumn(
				        AddUnitPrice,
				        "Value USD per KG",
				        each if [Net Weight KG] <> null and [Net Weight KG] > 0 and [Trade Value USD] <> null 
				             then [Trade Value USD] / [Net Weight KG] 
				             else null,
				        type number
				    ),
				
				    // 11. DATA TYPE CONVERSIONS
				    ChangedTypes = Table.TransformColumnTypes(
				        AddValuePerKg,
				        {
				            {"Year", Int64.Type},
				            {"Reporter Code", Int64.Type},
				            {"Partner Code", Int64.Type},
				            {"Reporter ISO", type text},
				            {"Partner ISO", type text},
				            {"Reporter", type text},
				            {"Partner", type text},
				            {"Flow", type text},
				            {"HS Code", type text},
				            {"HS Description", type text},
				            {"HS Classification", type text},
				            {"Vehicle Category", type text},
				            {"Sub Category", type text},
				            {"Quantity", type number},
				            {"Net Weight KG", type number},
				            {"Trade Value USD", type number},
				            {"FOB Value USD", type number},
				            {"CIF Value USD", type number},
				            {"Unit Price USD", type number},
				            {"Value USD per KG", type number}
				        },
				        "en-US"
				    ),
				
				    // 12. FINAL COLUMN SELECTION (Vehicle Category & Sub Category MUST be listed here)
				    FinalTable = Table.SelectColumns(
				        ChangedTypes,
				        {
				            "Year", "Reporter", "Flow", "Partner Code", "Partner ISO", "Partner",
				            "Vehicle Category", "Sub Category", "HS Code", "HS Description",
				            "HS Classification", "Trade Value USD", "FOB Value USD", "CIF Value USD",
				            "Quantity", "Quantity Unit", "Net Weight KG", "Unit Price USD", "Value USD per KG"
				        },
				        MissingField.UseNull
				    ),
				    #"Filtered Rows" = Table.SelectRows(FinalTable, each ([Partner] <> "China, Hong Kong SAR" and [Partner] <> "China, Macao SAR" and [Partner] <> "World")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Unit Price USD", Currency.Type}, {"CIF Value USD", Currency.Type}, {"FOB Value USD", Currency.Type}, {"Value USD per KG", Currency.Type}})
				in
				    #"Changed Type"
				```

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

